# Generated by Django 5.2.8 on 2025-11-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=255)),
                ('carbrand', models.CharField(max_length=255)),
                ('carmodel', models.CharField(max_length=255)),
                ('carprice', models.CharField(max_length=255)),
            ],
        ),
    ]
