# Generated by Django 5.2.8 on 2025-11-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcars',
            name='carbrand',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tbcars',
            name='carmodel',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tbcars',
            name='carname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tbcars',
            name='carprice',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='tbcars',
            table='TBCars',
        ),
    ]
