# Generated by Django 5.2.8 on 2025-11-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_tbcars_carbrand_alter_tbcars_carmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcars',
            name='carbrand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbcars',
            name='carmodel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbcars',
            name='carname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbcars',
            name='carprice',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='tbcars',
            table=None,
        ),
    ]
